name: mediastream.de
tagline:
url: http://www.mediastream.de


markdown: kramdown

kramdown:
  auto_ids: true
  parse_block_html: true

gems:

exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock

collections:
